---
title: "replicationGames"
author: "Steph, Sam, Iggy"
date: "2025-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load Packages
library(readr) # read csv file in
library(dplyr) # wrangling
library(tidyr) # Remove NAs in merged data
library(lubridate) # dates
library(sf) # foor reading .shp data

```

```{r}
# Setup - Load in data file
# set working directory as source file location
# Read in upzipped .csv data from "input" folder within

df1 <- read_csv("input/Data_2000-2016_county_monthly_combined.csv")
df2 <- rbind(
    read_csv("input/CompMort_01_08.csv"),
    read_csv("input/CompMort_09_16.csv")
)

# Merge data
df3 <- merge(
    mutate(df2, GEOID = `County Code`, year = Year),
    df1,
    all.x = TRUE,
    by = c("GEOID", "year")
) 

# Clean data
df4 <- df3 %>%
    mutate(
        CVD.adj = as.numeric(`Age Adjusted Rate`, na.rm = TRUE),
        GEOID = as.factor(GEOID)
        ) %>% # change column classes
    dplyr::select(
        c(
            GEOID,
            year_month,
            year,
            month,
            PM25,
            NO2,
            O3,
            Tmean,
            dewT,
            pop.total,
            pop.Male,
            pop.Female,
            pop.White,
            pop.Black,
            pop.Hispanic,
            CVD.adj
        )
    ) %>% # Select required columns
    drop_na() # Remove missing values
```

## Iggy Section

code goes here

```{r cars}
summary(cars)
```

## Steph Section


```{r}
# using packages dplyr, lubridate, & sf

data <- df1


## average PM2.5 (Figure 1a)
PM25.ave <- data %>%
  group_by(GEOID) %>%
  summarise(PM25_mean = mean(PM25))

## PM2.5 change (Figure 1b)
PM25.2000 <- data %>%
  filter(year==2000) %>%
  group_by(GEOID) %>%
  summarise(PM25_2000 = mean(PM25))

PM25.2016 <- data %>%
  filter(year==2016) %>%
  group_by(GEOID) %>%
  summarise(PM25_2016 = mean(PM25))

PM25.change <- PM25.2000 %>%
  left_join(PM25.2016, by=c("GEOID")) %>%
  mutate(PM25_chg = (PM25_2016 - PM25_2000)/PM25_2000 * 100) %>%
  dplyr::select(GEOID, PM25_chg)


## join with shapefile
PM25.ave$GEOID <- as.character(PM25.ave$GEOID)
PM25.change$GEOID <- as.character(PM25.change$GEOID)

US.county.F1 <- US.county %>%
  left_join(PM25.ave, by="GEOID") %>%
  left_join(PM25.change, by="GEOID")

```

## Sam Section

Code goes here